name: media_pro_example
description: Demonstrates how to use Media Pro.

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: ">=3.44.0"

dependencies:
  media_pro:
    path: ../
  nylo_support: ^7.29.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true