analyzer:
  exclude:
    - build/**

include: package:vibe_check/nylo.yaml
plugins:
  vibe_check:
    version: ^1.0.1
    diagnostics:
      swallowed_exception: warning
      redundant_null_check: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
