name: media_pro
description: "Media widgets for Flutter. Upload and display images from the gallery, camera and more."
version: 1.0.4
homepage: https://nylo.dev
repository: https://github.com/nylo-core/media-pro
issue_tracker: https://github.com/nylo-core/media-pro/issues
funding:
  - https://github.com/sponsors/agordn52
topics:
  - image-picker
  - media
  - api

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  http_parser: ^4.0.2
  pretty_dio_logger: ^1.3.1
  flutter_draggable_gridview: ^0.0.9
  dio: ^5.4.1
  nylo_support: ^5.51.0
  flutter:
    sdk: flutter
  mime: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
