name: media_pro
description: "Media widgets for Flutter. Upload and display images from the gallery, camera and more."
version: 2.0.0
homepage: https://nylo.dev
repository: https://github.com/nylo-core/media-pro
issue_tracker: https://github.com/nylo-core/media-pro/issues
funding:
  - https://github.com/sponsors/agordn52
topics:
  - image-picker
  - media
  - api

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  http_parser: ^4.0.2
  pretty_dio_logger: ^1.4.0
  flutter_draggable_gridview: ^0.0.12
  dio: ^5.7.0
  nylo_support: ^6.6.0
  flutter:
    sdk: flutter
  mime: ^2.0.0

dependency_overrides:
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
